name: Spelling

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-24.04' || fromJSON('["self-hosted","Linux","X64","arko","typetype"]') }}
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v6
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.47.2
